import Head from "next/head";
import React, { useContext } from "react";
import { useQuery } from "react-query";
import { userContext } from "../../src/contexts/UserContext";

const profile = () => {
  //    const { isLoading: roomLoading, data: room } = useQuery(
  //     ["", roomId],
  //     async () => {
  //       const data = await apiClient.get(`/room/${roomId}?userid=${user.userid}`);
  //       return data.data;
  //     },
  //     { enabled: !!user && !!roomId, refetchOnWindowFocus: false }
  //   );
  const { data: user, isLoading: userLoading } = useContext(userContext);
  const handleFollow = () => {};

  return !userLoading ? (
    <>
      <Head>
        <title>Myprofile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+Avestan&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="bg-zinc-800 font-display w-screen h-screen flex flex-row justify-center items-center relative">
        <div className="font-display text-white bg-zinc-800 w-screen h-screen flex flex-col justify-center items-center">
          <div className="mb-6 text-left w-1/3">
            <div className="mt-4">
              <div>
                <div className="flex items-center space-x-3">
                  <img
                    className="inline-block h-12 w-12 rounded-2xl active:opacity-80"
                    src={user.avatarurl}
                    alt=""
                  />

                  {user.userid !== user.userid && (
                    <button
                      onClick={handleFollow}
                      className="bg-gray-600 px-2 py-1 flex items-center justify-center rounded-md w-1/4 active:bg-gray-800 focus:outline-none focus:ring focus:ring-gray-300"
                    >
                      Follow
                    </button>
                  )}
                </div>
                <div className="flex flex-col items-start space-y-2 mt-2 mb-4 text-sm">
                  <div className="flex flex-col items-start">
                    <span>{user.username}</span>
                    <span>@{user.username}</span>
                  </div>
                  <div>
                    <span className="mr-3">
                      {/* {user.followers} Followers */}0 Followers
                    </span>
                    <span>
                      0 Following
                      {/* {user.following} Following */}
                    </span>
                  </div>
                  <span>{user.bio}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  ) : (
    <>Loading...</>
  );
};

export default profile;
