export const categories = [
  "🔧 Technology",
  "🎵 Music",
  "🎮 Gaming",
  "✈️ Travel",
  "📚 Books",
  "⚽️ Sports",
  "🎬 Movies",
  "🍔 Food",
  "💪 Fitness",
  "🎨 Art",
  "🌍 News",
  "💼 Business",
  "🧪 Science",
  "🎓 Education",
  "💰 Finance",
  "🏠 DIY",
  "🐾 Pets",
  "🌱 Environment",
  "🧘 Mental Health",
  "👗 Fashion",
  "🚗 Automotive",
  "🎭 Theater",
  "📸 Photography",
  "💻 Programming",
  "🎙️ Podcasts",
  "🌌 Astronomy",
  "🎪 Comedy",
  "🏛️ History",
  "⚖️ Politics",
  "🔮 Philosophy",
];

