import Head from "next/head";
import { useContext, useEffect } from "react";

const Callback = () => {
  useEffect(() => {
    if (window.opener && window.opener.location.pathname === "/login") {
      window.opener.location.replace("/home");
    } else {
      window.location.replace("/home");
    }

    if (window.opener) {
      window.close();
    }
  });
  return (
    <>
      <Head>
        <title>Streams | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>

        <link
          href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <div className="w-screen h-screen bg-app_bg_deepest text-white flex items-center justify-center">
        Please Wait ...{" "}
      </div>
    </>
  );
};

export default Callback;
