import type { NextPage } from "next";
import Head from "next/head";
import { useContext } from "react";
import { WebSocketContext } from "../src/contexts/WebsocketContext";
import { AiFillGithub } from "react-icons/ai";
import {
  Activity,
  Brackets,
  Code2,
  FileCode,
  Github,
  GithubIcon,
  Tag,
} from "lucide-react";
import { BsDiscord, BsGithub, BsGoogle } from "react-icons/bs";
import { BiLock } from "react-icons/bi";
import { MdLock } from "react-icons/md";
import { Button } from "@/components/ui/button";
import { GridOverlay } from "@/components/global/GridOverlay";
import useScreenType from "@/hooks/useScreenType";

const width = 400;
const height = 500;

const Home: NextPage = () => {
  const myDevice = useScreenType();

  const left =
    typeof window !== "undefined" && window.innerWidth / 2 - width / 2;
  const top =
    typeof window !== "undefined" && window.innerHeight / 2 - height / 2;

  const googleLogin = () => {
    myDevice == "isDesktop"
      ? window.open(
          `${
            process.env.NODE_ENV == "production"
              ? `${process.env.NEXT_PUBLIC_PROD_API}/auth/google`
              : `${process.env.NEXT_PUBLIC_DEV_API}/auth/google`
          }`,
          "",
          `toolbar=no, location=no, directories=no, status=no, menubar=no, 
  scrollbars=no, resizable=no, copyhistory=no, width=${width}, 
  height=${height}, top=${top}, left=${left}`
        )
      : window.location.replace(
          `${
            process.env.NODE_ENV == "production"
              ? `${process.env.NEXT_PUBLIC_PROD_API}/auth/google`
              : `${process.env.NEXT_PUBLIC_DEV_API}/auth/google`
          }`
        );
  };

  const discordLogin = () => {
    window.open(
      `${
        process.env.NODE_ENV == "production"
          ? `${process.env.NEXT_PUBLIC_PROD_API}/auth/discord`
          : `${process.env.NEXT_PUBLIC_DEV_API}/auth/discord`
      }`,
      "",
      `toolbar=no, location=no, directories=no, status=no, menubar=no, 
    scrollbars=no, resizable=no, copyhistory=no, width=${width}, 
    height=${height}, top=${top}, left=${left}`
    );
  };

  const githubLogin = () => {
    myDevice == "isDesktop"
      ? window.open(
          `${
            process.env.NODE_ENV == "production"
              ? `${process.env.NEXT_PUBLIC_PROD_API}/auth/github`
              : `${process.env.NEXT_PUBLIC_DEV_API}/auth/github`
          }`,
          "",
          `toolbar=no, location=no, directories=no, status=no, menubar=no, 
    scrollbars=no, resizable=no, copyhistory=no, width=${width}, 
    height=${height}, top=${top}, left=${left}`
        )
      : window.location.replace(
          `${
            process.env.NODE_ENV == "production"
              ? `${process.env.NEXT_PUBLIC_PROD_API}/auth/github`
              : `${process.env.NEXT_PUBLIC_DEV_API}/auth/github`
          }`
        );
  };

  const { conn } = useContext(WebSocketContext);

  return (
    <>
      <Head>
        <title>
          Chatterbox | Engaging voice conversations scaling to the moon,
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>

        <link
          href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <div className="w-screen h-screen text-white font-display bg-app_bg_deepest flex items-center justify-center">
        <GridOverlay />
        <div className="w-[450px] h-auto rounded-lg p-6 z-20">
          <div className="text-white flex flex-col items-center space-y-2 ">
            {/* <img src="/headphones.png" className="w-40" /> */}
            <span className="text-2xl font-bold text-center">
              Welcome to Streams ✨
            </span>
            <span className="text-center text-[12px] opacity-90 w-4/5">
              Create a new account on streams or{" "}
              <span className="text-green-400 cursor-pointer">log in </span> to
              an existing account to proceed
            </span>
          </div>
          <div className="text-white space-y-3 my-4">
            <Button
              onClick={() => {
                githubLogin();
              }}
              className="shadow-app_shadow bg-app_bg_deeper p-3 space-x-2 font-semibold flex items-center justify-center  rounded-md w-full"
            >
              <BsGithub size={17} style={{ marginRight: "1rem" }} />
              Continue with Github
            </Button>
            <Button
              onClick={() => {
                googleLogin();
              }}
              className="shadow-app_shadow bg-white p-3 font-semibold flex items-center justify-center  rounded-md w-full focus:outline-none focus:ring text-black hover:text-white"
            >
              <img src="/google.svg" width={"20px"} className="mr-[1rem]" />
              Continue with Google
            </Button>
            {/* <button className="bg-app_bg_deep p-3 font-semibold flex items-center justify-center  rounded-md w-full active:bg-sky-800 focus:outline-none focus:ring focus:ring-sky-300">
              <BsDiscord size={16} style={{ marginRight: "1rem" }} />
              Log in with Discord
            </button> */}
          </div>
        </div>

        <footer className="z-10 py-7 px-10 fixed bottom-0 left-0 w-full flex justify-center items-center space-x-10">
          <h1 className="font-logo text-[1rem] leading-[2.3rem] flex items-center relative cursor-pointer">
            <img src="/logo.svg" width={25} className="mr-2" />
            <span className="relative">
              Streams
              <span className="absolute text-[8px] px-1 text-green-400">
                Beta
              </span>
            </span>
          </h1>
          <a
            target="_blank"
            href="https://github.com/Nginze/streams"
            className="text-sm flex items-center opacity-70"
          >
            <Code2 className="mr-1 opacity-70" size={17} />
            Github
          </a>
        </footer>
      </div>

      {/* <div className="font-display text-white bg-zinc-800 w-screen h-screen flex flex-col justify-center items-center">
        <div className="mb-6 text-left w-1/3">
          <h1 className="font-bold text-4xl mb-3">Welcome to Drop 🎧</h1>
          <p className="font-bold text-2xl">
            Taking drop-in audio conversations to the moon 🚀
          </p>
        </div>
        <div className="flex flex-col w-1/3  mb-6 text-left text-lg">
          <span className="mb-3">🗸 Dark Theme</span>
          <span className="mb-3">🗸 Open Sign-ups</span>
          <span className="mb-3">🗸 Text Chat</span>
          <span className="mb-3">🗸 Scaling to the Moon</span>
        </div>
        <div className="w-1/3">
          <button
            onClick={() => {
              githubLogin();
            }}
            className="bg-sky-600 p-3 flex items-center justify-center font-bold rounded-md w-full active:bg-sky-800 focus:outline-none focus:ring focus:ring-sky-300"
          >
            <span className="mr-3">
              <AiFillGithub color="white" fontSize={"1.7rem"} />
            </span>
            Login with Github
          </button>
        </div>
      </div> */}
    </>
    // <div className="text-white flex min-h-screen flex-col items-center justify-center py-2 overflow-x-hidden">
    // </div>
  );
};

export default Home;
