import type { NextPage } from "next";
import Head from "next/head";
import { useContext } from "react";
import { WebSocketContext } from "../src/contexts/WebsocketContext";
import { AiFillGithub } from "react-icons/ai";

const BACKEND_URI = "http://localhost:8000";
const width = 600;
const height = 600;

const Home: NextPage = () => {
  const left =
    typeof window !== "undefined" && window.innerWidth / 2 - width / 2;
  const top =
    typeof window !== "undefined" && window.innerHeight / 2 - height / 2;

  const googleLogin = () => {
    window.open(
      BACKEND_URI + "/auth/google",
      "",
      `toolbar=no, location=no, directories=no, status=no, menubar=no, 
  scrollbars=no, resizable=no, copyhistory=no, width=${width}, 
  height=${height}, top=${top}, left=${left}`
    );
  };

  const discordLogin = () => {
    window.open(
      BACKEND_URI + "/auth/discord",
      "",
      `toolbar=no, location=no, directories=no, status=no, menubar=no, 
    scrollbars=no, resizable=no, copyhistory=no, width=${width}, 
    height=${height}, top=${top}, left=${left}`
    );
  };

  const githubLogin = () => {
    window.open(
      BACKEND_URI + "/auth/github",
      "",
      `toolbar=no, location=no, directories=no, status=no, menubar=no, 
    scrollbars=no, resizable=no, copyhistory=no, width=${width}, 
    height=${height}, top=${top}, left=${left}`
    );
  };

  const { conn } = useContext(WebSocketContext);
  console.log(conn);
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+Avestan&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="font-display text-white bg-zinc-800 w-screen h-screen flex flex-col justify-center items-center">
        <div className="mb-6 text-left w-1/3">
          <h1 className="font-bold text-4xl mb-3">Welcome to Drop 🎧</h1>
          <p className="font-bold text-2xl">
            Taking drop-in audio conversations to the moon 🚀
          </p>
        </div>
        <div className="flex flex-col w-1/3  mb-6 text-left text-lg">
          <span className="mb-3">🗸 Dark Theme</span>
          <span className="mb-3">🗸 Open Sign-ups</span>
          <span className="mb-3">🗸 Text Chat</span>
          <span className="mb-3">🗸 Scaling to the Moon</span>
        </div>
        <div className="w-1/3">
          <button
            onClick={() => {
              githubLogin();
            }}
            className="bg-sky-600 p-3 flex items-center justify-center font-bold rounded-md w-full active:bg-sky-800 focus:outline-none focus:ring focus:ring-sky-300"
          >
            <span className="mr-3">
              <AiFillGithub color="white" fontSize={"1.7rem"} />
            </span>
            Login with Github
          </button>
        </div>
      </div>
    </>
    // <div className="text-white flex min-h-screen flex-col items-center justify-center py-2 overflow-x-hidden">
    // </div>
  );
};

export default Home;
