import type { NextPage } from "next";
import Head from "next/head";
import { useContext } from "react";
import { WebSocketContext } from "../src/contexts/WebsocketContext";
import { AiFillGithub } from "react-icons/ai";
import {
  Activity,
  Brackets,
  Code2,
  FileCode,
  Github,
  GithubIcon,
  Tag,
} from "lucide-react";
import { BsDiscord, BsGithub, BsGoogle } from "react-icons/bs";
import { BiLock } from "react-icons/bi";
import { MdLock } from "react-icons/md";

const BACKEND_URI = "http://localhost:8000";
const width = 600;
const height = 600;

const Home: NextPage = () => {
  const left =
    typeof window !== "undefined" && window.innerWidth / 2 - width / 2;
  const top =
    typeof window !== "undefined" && window.innerHeight / 2 - height / 2;

  const googleLogin = () => {
    window.open(
      BACKEND_URI + "/auth/google",
      "",
      `toolbar=no, location=no, directories=no, status=no, menubar=no, 
  scrollbars=no, resizable=no, copyhistory=no, width=${width}, 
  height=${height}, top=${top}, left=${left}`
    );
  };

  const discordLogin = () => {
    window.open(
      BACKEND_URI + "/auth/discord",
      "",
      `toolbar=no, location=no, directories=no, status=no, menubar=no, 
    scrollbars=no, resizable=no, copyhistory=no, width=${width}, 
    height=${height}, top=${top}, left=${left}`
    );
  };

  const githubLogin = () => {
    window.open(
      BACKEND_URI + "/auth/github",
      "",
      `toolbar=no, location=no, directories=no, status=no, menubar=no, 
    scrollbars=no, resizable=no, copyhistory=no, width=${width}, 
    height=${height}, top=${top}, left=${left}`
    );
  };

  const { conn } = useContext(WebSocketContext);
  console.log(conn);
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>

        <link
          href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <div className="w-screen h-screen text-white font-display bg-app_bg_deepest flex items-center justify-center">
        <div className="w-[350px] space-y-3 h-auto bg-app_bg_deeper rounded-lg p-6">
          <div className="text-white flex flex-col items-start space-y-2 ">
            <span className="text-2xl font-bold">Welcome</span>
            <span className="text-[12px]">
              By logging in you accept our Privacy Policy and Terms of Service.
            </span>
          </div>
          <div className="text-white space-y-3 my-2">
            <button
              onClick={() => {
                githubLogin();
              }}
              className="bg-app_bg_deep p-3 space-x-2 font-semibold flex items-center justify-center  rounded-md w-full active:bg-sky-800 focus:outline-none focus:ring focus:ring-sky-300"
            >
              <BsGithub size={17} style={{ marginRight: "1rem" }} />
              Log in with Github
            </button>
            <button className="bg-app_bg_deep p-3 font-semibold flex items-center justify-center  rounded-md w-full active:bg-sky-800 focus:outline-none focus:ring focus:ring-sky-300">
              <BsGoogle size={16} style={{ marginRight: "1rem" }} />
              Log in with Google
            </button>
            <button className="bg-app_bg_deep p-3 font-semibold flex items-center justify-center  rounded-md w-full active:bg-sky-800 focus:outline-none focus:ring focus:ring-sky-300">
              <BsDiscord size={16} style={{ marginRight: "1rem" }} />
              Log in with Discord
            </button>
          </div>
        </div>

        <footer className="py-7 px-10 fixed bottom-0 left-0 w-full flex justify-between items-center space-x-10">
          <h1 className="font-logo text-[1.5rem] leading-[2.3rem] flex items-center relative">
            <Activity size={20} className="mr-2" color="#7289da" />
            chatterbox
          </h1>
          <div className="flex items-baseline space-x-6 leading=[2.3em]">
            <a
              target="_blank"
              href="https://github.com/Nginze/drop-next"
              className="text-sm flex items-center text-[#424549]"
            >
              <Code2 className="mr-1" color="#424549" size={17} />
              Github
            </a>

            <a className="text-sm flex items-center text-[#424549] ">
              <FileCode className="mr-1" color="#424549" size={17} />
              Terms
            </a>

            <a className="text-sm flex items-center text-[#424549]">
              <MdLock className="mr-1" color="#424549" size={17} />
              Privacy
            </a>
          </div>
        </footer>
      </div>

      {/* <div className="font-display text-white bg-zinc-800 w-screen h-screen flex flex-col justify-center items-center">
        <div className="mb-6 text-left w-1/3">
          <h1 className="font-bold text-4xl mb-3">Welcome to Drop 🎧</h1>
          <p className="font-bold text-2xl">
            Taking drop-in audio conversations to the moon 🚀
          </p>
        </div>
        <div className="flex flex-col w-1/3  mb-6 text-left text-lg">
          <span className="mb-3">🗸 Dark Theme</span>
          <span className="mb-3">🗸 Open Sign-ups</span>
          <span className="mb-3">🗸 Text Chat</span>
          <span className="mb-3">🗸 Scaling to the Moon</span>
        </div>
        <div className="w-1/3">
          <button
            onClick={() => {
              githubLogin();
            }}
            className="bg-sky-600 p-3 flex items-center justify-center font-bold rounded-md w-full active:bg-sky-800 focus:outline-none focus:ring focus:ring-sky-300"
          >
            <span className="mr-3">
              <AiFillGithub color="white" fontSize={"1.7rem"} />
            </span>
            Login with Github
          </button>
        </div>
      </div> */}
    </>
    // <div className="text-white flex min-h-screen flex-col items-center justify-center py-2 overflow-x-hidden">
    // </div>
  );
};

export default Home;
