export const emojis = [
  {
    id: "heart",
    name: "heart",
    short_names: ["heart", "<3"],
    keywords: ["heart", "<3"],
    skins: [{ src: "/emotes/heart.png" }],
  },
  {
    name: "brokenheart",
    id: "brokenheart",
    short_names: ["brokenHeart"],
    keywords: ["broken", "heart", "broken heart", "brokenHeart"],
    skins: [{ src: "/emotes/brokenHeart.gif" }],
  },
  {
    name: "obama",
    id: "obama",
    short_names: ["obama"],
    keywords: ["obama", "prism", "obamium"],
    skins: [{ src: "/emotes/obamium.png" }],
  },
  {
    name: "intelxamd",
    id: "intelxamd",
    short_names: ["intelxamd"],
    keywords: ["intel", "amd", "intelxamd"],
    skins: [{ src: "/emotes/IntelxAMD.png" }],
  },
  {
    name: "linus",
    id: "linus",
    short_names: ["linus"],
    keywords: ["linus", "tech", "linustechtips"],
    skins: [{ src: "/emotes/linus.png" }],
  },
  {
    name: "reddogehouse",
    id: "reddogehouse",
    short_names: ["redDogeHouse"],
    keywords: ["red", "dogehouse", "doge"],
    skins: [{ src: "/emotes/reddogehouse.png" }],
  },
  {
    name: "this",
    id: "this",
    short_names: ["this"],
    keywords: ["this"],
    skins: [{ src: "/emotes/this.png" }],
  },
  {
    name: "browndogehouse",
    id: "browndogehouse",
    short_names: ["brownDogeHouse"],
    keywords: ["brown", "dogehouse", "doge"],
    skins: [{ src: "/emotes/browndogehouse.png" }],
  },
  {
    name: "shut",
    id: "shut",
    short_names: ["shut"],
    keywords: ["shut"],
    skins: [{ src: "/emotes/shut.png" }],
  },
  {
    name: "blobwtf",
    id: "blobwtf",
    short_names: ["blobWtf"],
    keywords: ["blob", "wtf"],
    skins: [{ src: "/emotes/blobwtf.png" }],
  },
  {
    name: "whalethonk",
    id: "whalethonk",
    short_names: ["WhaleThonk"],
    keywords: ["whale", "thonk", "thinking", "what"],
    skins: [{ src: "/emotes/whalethonk.png" }],
  },
  {
    name: "pogchamp",
    short_names: ["PogChamp"],
    id: "pogchamp",
    keywords: ["pogchamp", "pog"],
    skins: [{ src: "/emotes/pogchamp.png" }],
  },
  {
    name: "monkas",
    id: "monkas",
    short_names: ["monkaS"],
    keywords: ["monkas", "pepe"],
    skins: [{ src: "/emotes/monkas.png" }],
  },
  {
    name: "hypers",
    short_names: ["HYPERS"],
    id: "hypers",
    keywords: ["hypers", "pepe"],
    skins: [{ src: "/emotes/hypers.png" }],
  },
  {
    name: "peped",
    id: "peped",
    short_names: ["pepeD"],
    keywords: ["peped", "pepe"],
    skins: [{ src: "/emotes/peped.gif" }],
  },
  {
    name: "pepega",
    id: "pepega",
    short_names: ["Pepega"],
    keywords: ["pepega", "pepe"],
    skins: [{ src: "/emotes/pepega.png" }],
  },
  {
    name: "peepohappy",
    id: "peepohappy",
    short_names: ["peepoHappy"],
    keywords: ["peepohappy", "peepo", "pepe"],
    skins: [{ src: "/emotes/peepohappy.png" }],
  },
  {
    name: "peepohug",
    id: "peepohug",
    short_names: ["peepoHug"],
    keywords: ["peepohug", "peepo", "pepe"],
    skins: [{ src: "/emotes/peepohug.png" }],
  },
  {
    name: "sadge",
    id: "sadge",
    short_names: ["Sadge"],
    keywords: ["sadge", "pepe"],
    skins: [{ src: "/emotes/sadge.png" }],
  },
  {
    name: "catjam",
    id: "catjam",
    short_names: ["catJAM"],
    keywords: ["catjam", "vibe"],
    skins: [{ src: "/emotes/catjam.gif" }],
  },
  {
    name: "thonk",
    id: "thonk",
    short_names: ["Thonk"],
    keywords: ["thonk", "think"],
    skins: [{ src: "/emotes/thonk.png" }],
  },
  {
    name: "dogehouse",
    id: "dogehouse",
    short_names: ["DogeHouse"],
    keywords: ["dogehouse", "doge"],
    skins: [{ src: "/emotes/dogehouse.png" }],
  },
  {
    name: "sadhouse",
    id: "sadhouse",
    short_names: ["SadHouse"],
    keywords: ["dogehouse", "doge", "sadhouse"],
    skins: [{ src: "/emotes/sadhouse.png" }],
  },
  {
    name: "coolhouse",
    id: "coolhouse",
    short_names: ["CoolHouse"],
    keywords: ["dogehouse", "doge", "coolhouse"],
    skins: [{ src: "/emotes/coolhouse.png" }],
  },
  {
    name: "winkhouse",
    id: "winkhouse",
    short_names: ["WinkHouse"],
    keywords: ["dogehouse", "doge", "winkhouse"],
    skins: [{ src: "/emotes/winkhouse.png" }],
  },
  {
    name: "suprisehouse",
    id: "suprisehouse",
    short_names: ["SupriseHouse"],
    keywords: ["dogehouse", "doge", "suprisehouse", "shock"],
    skins: [{ src: "/emotes/suprisehouse.png" }],
  },
  {
    name: "neutralhouse",
    id: "neutralhouse",
    short_names: ["NeutralHouse"],
    keywords: ["dogehouse", "doge", "neutralhouse"],
    skins: [{ src: "/emotes/neutralhouse.png" }],
  },
  {
    name: "waytoodank",
    id: "waytoodank",
    short_names: ["WAYTOODANK"],
    keywords: ["dank", "feelsdankman", "waytoodank"],
    skins: [{ src: "/emotes/waytoodank.gif" }],
  },
  {
    name: "cryptobtc",
    id: "cryptobtc",
    short_names: ["CryptoBTC"],
    keywords: ["crypto", "btc", "bitcoin"],
    skins: [{ src: "/emotes/cryptoBTC.png" }],
  },
  {
    name: "cryptoeth",
    id: "cryptoeth",
    short_names: ["CryptoETH"],
    keywords: ["crypto", "eth", "ethereum"],
    skins: [{ src: "/emotes/cryptoETH.png" }],
  },
  {
    name: "cryptobnb",
    id: "cryptobnb",
    short_names: ["CryptoBNB"],
    keywords: ["crypto", "bnb", "binance"],
    skins: [{ src: "/emotes/cryptoBNB.png" }],
  },
  {
    name: "cryptoltc",
    id: "cryptoltc",
    short_names: ["CryptoLTC"],
    keywords: ["crypto", "ltc", "litecoin"],
    skins: [{ src: "/emotes/cryptoLTC.png" }],
  },
  {
    name: "cryptobch",
    id: "cryptobch",
    short_names: ["CryptoBCH"],
    keywords: ["crypto", "bch", "bitcoin", "bitcoincash"],
    skins: [{ src: "/emotes/cryptoBCH.png" }],
  },
  {
    name: "cryptodoge",
    id: "cryptodoge",
    short_names: ["CryptoDOGE"],
    keywords: ["crypto", "doge", "dogecoin", "bestcoin"],
    skins: [{ src: "/emotes/cryptoDOGE.png" }],
  },
  {
    name: "cryptosushi",
    id: "cryptosushi",
    short_names: ["CryptoSUSHI"],
    keywords: ["crypto", "sushi", "swap", "sushiswap"],
    skins: [{ src: "/emotes/cryptoSUSHI.png" }],
  },
  {
    name: "cryptotron",
    id: "cryptotron",
    short_names: ["CryptoTRON"],
    keywords: ["crypto", "tron"],
    skins: [{ src: "/emotes/cryptoTron.png" }],
  },
  {
    name: "cryptozec",
    id: "cryptozec",
    short_names: ["CryptoZEC"],
    keywords: ["crypto", "zec", "zcash"],
    skins: [{ src: "/emotes/cryptoZEC.png" }],
  },
  {
    name: "cryptoetc",
    id: "cryptoetc",
    short_names: ["CryptoETC"],
    keywords: ["crypto", "etc", "ethereum", "ethereumclassic"],
    skins: [{ src: "/emotes/cryptoETC.png" }],
  },
  {
    name: "cryptocake",
    id: "cryptocake",
    short_names: ["CryptoCAKE"],
    keywords: ["crypto", "cake", "swap", "pancakeswap"],
    skins: [{ src: "/emotes/cryptoCAKE.png" }],
  },
  {
    name: "cryptoada",
    short_names: ["CryptoADA"],
    keywords: ["crypto", "ada", "cardano"],
    skins: [{ src: "/emotes/cryptoADA.png" }],
  },
  {
    name: "cryptoxrp",
    short_names: ["CryptoXRP"],
    keywords: ["crypto", "xrp", "ripple"],
    skins: [{ src: "/emotes/cryptoXRP.png" }],
  },
  {
    name: "cryptousdc",
    short_names: ["CryptoUSDC"],
    keywords: ["crypto", "usdc", "usdcoin"],
    skins: [{ src: "/emotes/cryptoUSDC.png" }],
  },
  {
    name: "dodgycoin",
    short_names: ["DodgyCoin"],
    keywords: ["crypto", "doge", "dodgycoin"],
    skins: [{ src: "/emotes/dodgyCoin.png" }],
  },
  {
    name: "pepebckl",
    id: "pepebckl",
    short_names: ["pepeBCKL"],
    keywords: [
      "pepebckl",
      "bckl",
      "pepe",
      "malarkey",
      "jesse",
      "penguin",
      "stallman",
      "freesoftware",
      "fsf",
      "charlie",
      "kernel",
      "lab",
      "kernellab",
      "computing",
      "jessecharlie",
      "linux",
      "torvalds",
    ],
    skins: [{ src: "/emotes/pepeBCKL.png" }],
  },
  {
    name: "5head",
    id: "5head",
    short_names: ["5Head"],
    keywords: ["5head", "big", "brain", "bigbrain", "smart"],
    skins: [{ src: "/emotes/5Head.png" }],
  },
  {
    name: "ayaya",
    id: "ayaya",
    short_names: ["AYAYA"],
    keywords: ["ayaya"],
    skins: [{ src: "/emotes/AYAYA.png" }],
  },
  {
    name: "babayep",
    id: "babayep",
    short_names: ["babaYEP"],
    keywords: ["babayep", "baba", "yep"],
    skins: [{ src: "/emotes/babaYEP.png" }],
  },
  {
    name: "bboomer",
    id: "bboomer",
    short_names: ["BBoomer"],
    keywords: ["bboomer", "boomer"],
    skins: [{ src: "/emotes/BBoomer.gif" }],
  },
  {
    name: "bebela",
    id: "bebela",
    short_names: ["BebeLa"],
    keywords: ["bebela", "bebe"],
    skins: [{ src: "/emotes/BebeLa.png" }],
  },
  {
    name: "bern",
    id: "bern",
    short_names: ["BERN"],
    keywords: [
      "bern",
      "notmeus",
      "bernie",
      "sanders",
      "berniesanders",
      "bernard",
      "socialism",
      "socialist",
      "comrade",
      "democrat",
      "malarkey",
      "biden",
      "joe",
      "joebiden",
      "us",
      "usa",
      "america",
    ],
    skins: [{ src: "/emotes/BERN.png" }],
  },
  {
    name: "bidenjam",
    id: "bidenjam",
    short_names: ["bidenJAM"],
    keywords: [
      "bidenjam",
      "jam",
      "jamjam",
      "malarkey",
      "ridinwithbiden",
      "icecream",
      "joe",
      "biden",
      "joebiden",
      "46",
      "president",
      "laser",
      "potus",
      "democrat",
      "us",
      "usa",
      "america",
    ],
    skins: [{ src: "/emotes/bidenJAM.gif" }],
  },
  {
    name: "playa",
    id: "playa",
    short_names: ["Playa"],
    keywords: ["Playa"],
    skins: [{ src: "/emotes/Playa.png" }],
  },
  {
    name: "igetit",
    id: "igetit",
    short_names: ["IGetIt"],
    keywords: ["IGetIt", "Smile", "PepeLa", "Smug"],
    skins: [{ src: "/emotes/IGetIt.png" }],
  },
  {
    name: "blankies",
    id: "blankies",
    short_names: ["BLANKIES"],
    keywords: ["blankies", "jammies", "blanket", "dance"],
    skins: [{ src: "/emotes/BLANKIES.gif" }],
  },
  {
    name: "bogged",
    short_names: ["BOGGED"],
    keywords: [
      "bogged",
      "bog",
      "hello",
      "phone",
      "iphone",
      "calling",
      "call",
      "phonecall",
    ],
    skins: [{ src: "/emotes/BOGGED.png" }],
  },
  {
    name: "clap",
    short_names: ["Clap"],
    keywords: ["clap", "clapping"],
    skins: [{ src: "/emotes/Clap.gif" }],
  },
  {
    name: "coggers",
    short_names: ["COGGERS"],
    keywords: ["coggers", "pog", "pogu", "poggies", "poggers", "pogger"],
    skins: [{ src: "/emotes/COGGERS.gif" }],
  },
  {
    name: "copium",
    short_names: ["COPIUM"],
    keywords: ["copium", "cope"],
    skins: [{ src: "/emotes/COPIUM.png" }],
  },
  {
    name: "coronas",
    short_names: ["coronaS"],
    keywords: ["coronas", "corona", "mask", "covid"],
    skins: [{ src: "/emotes/coronaS.png" }],
  },
  {
    name: "crabpls",
    short_names: ["CrabPls"],
    keywords: ["crabpls", "crab", "pls", "plz", "please"],
    skins: [{ src: "/emotes/crabpls.gif" }],
  },
  {
    name: "dankhackermans",
    short_names: ["DANKHACKERMANS"],
    keywords: [
      "dankhackermans",
      "dank",
      "hacker",
      "hackermans",
      "keyboard",
      "typing",
      "computer",
      "coding",
      "coder",
      "code",
      "virus",
      "malware",
    ],
    skins: [{ src: "/emotes/DANKHACKERMANS.gif" }],
  },
  {
    name: "dankhug",
    short_names: ["dankHug"],
    keywords: ["dankhug", "dank", "hug"],
    skins: [{ src: "/emotes/dankHug.png" }],
  },
  {
    name: "dankies",
    short_names: ["DANKIES"],
    keywords: ["dankies", "dank"],
    skins: [{ src: "/emotes/DANKIES.gif" }],
  },
  {
    name: "dewtime",
    short_names: ["DewTime"],
    keywords: ["dewtime", "mountaindew", "dew", "moutain", "time"],
    skins: [{ src: "/emotes/DewTime.gif" }],
  },
  {
    name: "ez",
    short_names: ["EZ"],
    keywords: ["ez"],
    skins: [{ src: "/emotes/EZ.png" }],
  },
  {
    name: "f",
    short_names: ["F"],
    keywords: ["f"],
    skins: [{ src: "/emotes/F.gif" }],
  },
  {
    name: "feelsdankman",
    short_names: ["FeelsDankMan"],
    keywords: ["feelsdankman", "feels", "feel", "dank", "man"],
    skins: [{ src: "/emotes/FeelsDankMan.png" }],
  },
  {
    name: "feelsokayman",
    short_names: ["FeelsOkayMan"],
    keywords: ["feelsokayman", "feels", "feel", "okay", "man"],
    skins: [{ src: "/emotes/FeelsOkayMan.png" }],
  },
  {
    name: "feelsstrongman",
    short_names: ["FeelsStrongMan"],
    keywords: ["feelsstrongman", "feels", "feel", "strong", "man"],
    skins: [{ src: "/emotes/FeelsStrongMan.png" }],
  },
  {
    name: "feelsweirdman",
    short_names: ["FeelsWeirdMan"],
    keywords: ["feelsweirdman", "feels", "feel", "weird", "man"],
    skins: [{ src: "/emotes/FeelsWeirdMan.png" }],
  },
  {
    name: "gachihyper",
    short_names: ["gachiHYPER"],
    keywords: ["gachihyper", "gachi", "hyper", "coomer"],
    skins: [{ src: "/emotes/gachiHYPER.gif" }],
  },
  {
    name: "grug",
    short_names: ["GRUG"],
    keywords: ["grug"],
    skins: [{ src: "/emotes/GRUG.png" }],
  },
  {
    name: "guitartime",
    short_names: ["GuitarTime"],
    keywords: ["guitartime", "guitar", "time"],
    skins: [{ src: "/emotes/GuitarTime.gif" }],
  },
  {
    name: "hackermans",
    short_names: ["HACKERMANS"],
    keywords: [
      "hackermans",
      "hacker",
      "keyboard",
      "typing",
      "computer",
      "coding",
      "coder",
      "code",
      "virus",
      "malware",
    ],
    skins: [{ src: "/emotes/HACKERMANS.gif" }],
  },
  {
    name: "handsup",
    short_names: ["HandsUp"],
    keywords: ["handsup", "hands", "up", "hand"],
    skins: [{ src: "/emotes/HandsUp.png" }],
  },
  {
    name: "hasanhypersmash",
    short_names: ["hasanHyperSmash"],
    keywords: [
      "hasanhypersmash",
      "hasan",
      "hasanabi",
      "hasanpiker",
      "hyper",
      "smash",
    ],
    skins: [{ src: "/emotes/hasanHyperSmash.gif" }],
  },
  {
    name: "hasansmash",
    short_names: ["hasanSmash"],
    keywords: ["hasansmash", "hasan", "hasanabi", "hasanpiker", "smash"],
    skins: [{ src: "/emotes/hasanSmash.gif" }],
  },
  {
    name: "hasanwalk",
    short_names: ["HasanWalk"],
    keywords: [
      "hasanwalk",
      "hasan",
      "hasanabi",
      "hasanpiker",
      "walk",
      "walking",
    ],
    skins: [{ src: "/emotes/HasanWalk.gif" }],
  },
  {
    name: "hashyperjam",
    short_names: ["hasHyperJAM"],
    keywords: [
      "hashyperjam",
      "hasan",
      "hasanabi",
      "hasanpiker",
      "hyper",
      "jam",
      "jamjam",
      "jammies",
    ],
    skins: [{ src: "/emotes/hasHyperJAM.gif" }],
  },
  {
    name: "haspls",
    short_names: ["hasPls"],
    keywords: [
      "haspls",
      "please",
      "pls",
      "plz",
      "hasan",
      "hasanabi",
      "hasanpiker",
    ],
    skins: [{ src: "/emotes/hasPls.gif" }],
  },
  {
    name: "hasrock",
    short_names: ["hasRock"],
    keywords: [
      "hasrock",
      "spongebob",
      "patrick",
      "hasan",
      "hasanabi",
      "hasanpiker",
      "rock",
    ],
    skins: [{ src: "/emotes/hasRock.gif" }],
  },
  {
    name: "hastasty",
    short_names: ["hasTasty"],
    keywords: [
      "hastasty",
      "hasan",
      "tasty",
      "yum",
      "yummy",
      "hasanabi",
      "hasanpiker",
    ],
    skins: [{ src: "/emotes/hasTasty.gif" }],
  },
  {
    name: "hyperclap",
    short_names: ["HYPERCLAP"],
    keywords: ["hyperclap", "hyper", "clap"],
    skins: [{ src: "/emotes/HYPERCLAP.gif" }],
  },
  {
    name: "hyperhammer",
    short_names: ["hyperHammer"],
    keywords: ["hyperhammer", "hyper", "hammer"],
    skins: [{ src: "/emotes/hyperHammer.gif" }],
  },
  {
    name: "hyperitalianhands",
    short_names: ["HYPERITALIANHANDS"],
    keywords: [
      "hyperitalianhands",
      "hyper",
      "italian",
      "hands",
      "hand",
      "italy",
      "ovahere",
    ],
    skins: [{ src: "/emotes/HYPERITALIANHANDS.gif" }],
  },
  {
    name: "hyperpogger",
    short_names: ["HYPERPOGGER"],
    keywords: ["hyperpogger", "hyper", "pog", "pogger", "poggies"],
    skins: [{ src: "/emotes/HYPERPOGGER.gif" }],
  },
  {
    name: "hyperpogo",
    short_names: ["HYPERPOGO"],
    keywords: [
      "hyperpogo",
      "hyper",
      "pog",
      "pogo",
      "azan",
      "poggies",
      "poggers",
      "pogger",
    ],
    skins: [{ src: "/emotes/HYPERPOGO.gif" }],
  },
  {
    name: "italianhands",
    short_names: ["ItalianHands"],
    keywords: ["italianhands", "ovahere", "italian", "hands", "hand", "italy"],
    skins: [{ src: "/emotes/ItalianHands.gif" }],
  },
  {
    name: "jammies",
    short_names: ["Jammies"],
    keywords: ["jammies", "jam", "jamjam", "dance", "vibe"],
    skins: [{ src: "/emotes/Jammies.gif" }],
  },
  {
    name: "kekw",
    short_names: ["KEKW"],
    keywords: [
      "kekw",
      "kek",
      "omegalul",
      "lol",
      "lmao",
      "haha",
      "ha",
      "ja",
      "jaja",
    ],
    skins: [{ src: "/emotes/KEKW.png" }],
  },
  {
    name: "kekwait",
    short_names: ["KEKWait"],
    keywords: [
      "kekwait",
      "lul",
      "omegalul",
      "lol",
      "lmao",
      "wait",
      "kek",
      "ha",
    ],
    skins: [{ src: "/emotes/KEKWait.png" }],
  },
  {
    name: "kkapitalist",
    short_names: ["KKapitalist"],
    keywords: ["kkapitalist", "kapitalist", "capitalist", "business"],
    skins: [{ src: "/emotes/KKapitalist.png" }],
  },
  {
    name: "kkomrade",
    short_names: ["KKomrade"],
    keywords: ["kkomrade", "komrade", "comrade"],
    skins: [{ src: "/emotes/KKomrade.png" }],
  },
  {
    name: "kkonaw",
    short_names: ["KKonaW"],
    keywords: ["kkonaw"],
    skins: [{ src: "/emotes/KKonaW.png" }],
  },
  {
    name: "kkop",
    short_names: ["KKop"],
    keywords: [
      "kkop",
      "kop",
      "kops",
      "cop",
      "cops",
      "police",
      "acab",
      "blueline",
    ],
    skins: [{ src: "/emotes/KKop.png" }],
  },
  {
    name: "lulw",
    short_names: ["LULW"],
    keywords: ["lulw", "lul", "lol", "lmao", "omegalul"],
    skins: [{ src: "/emotes/LULW.png" }],
  },
  {
    name: "lulwut",
    short_names: ["lulWut"],
    keywords: [
      "lulwut",
      "lul",
      "lmao",
      "lol",
      "wut",
      "what",
      "wat",
      "wtf",
      "omegalul",
      "ha",
      "haha",
      "ja",
      "jaja",
    ],
    skins: [{ src: "/emotes/lulWut.png" }],
  },
  {
    name: "malarkey",
    short_names: ["MALARKEY"],
    keywords: [
      "malarkey",
      "ridinwithbiden",
      "icecream",
      "joe",
      "biden",
      "joebiden",
      "46",
      "president",
      "laser",
      "potus",
      "democrat",
      "us",
      "usa",
      "america",
    ],
    skins: [{ src: "/emotes/MALARKEY.gif" }],
  },
  {
    name: "mmmhmm",
    short_names: ["MmmHmm"],
    keywords: [
      "mmmhmm",
      "mmm",
      "mmmm",
      "hmm",
      "hmmm",
      "mmmmhmmm",
      "mmmmhmm",
      "mmmhmmm",
    ],
    skins: [{ src: "/emotes/MmmHmm.gif" }],
  },
  {
    name: "modcheck",
    short_names: ["modCheck"],
    keywords: [
      "modcheck",
      "mods",
      "mod",
      "check",
      "spongebob",
      "ask",
      "askers",
      "whoasked",
      "where",
      "look",
      "fish",
      "oooo",
    ],
    skins: [{ src: "/emotes/modCheck.gif" }],
  },
  {
    name: "modtime",
    short_names: ["ModTime"],
    keywords: ["modtime", "mod", "mods", "time"],
    skins: [{ src: "/emotes/ModTime.gif" }],
  },
  {
    name: "monkahmm",
    short_names: ["monkaHmm"],
    keywords: ["monkahmm", "monka", "hmmm", "hmm"],
    skins: [{ src: "/emotes/monkaHmm.png" }],
  },
  {
    name: "monkastare",
    short_names: ["monkaStare"],
    keywords: ["monkastare", "stare", "monka"],
    skins: [{ src: "/emotes/monkaStare.png" }],
  },
  {
    name: "monkasteer",
    short_names: ["monkaSTEER"],
    keywords: ["monkasteer", "monka", "steer", "ridinwithbiden"],
    skins: [{ src: "/emotes/monkaSTEER.gif" }],
  },
  {
    name: "monkaw",
    short_names: ["monkaW"],
    keywords: ["monkaw", "monka"],
    skins: [{ src: "/emotes/monkaW.png" }],
  },
  {
    name: "neffhyperjam",
    short_names: ["neffHyperJAM"],
    keywords: [
      "neffhyperjam",
      "hyperjam",
      "jam",
      "jammies",
      "boppin",
      "dj",
      "jamjam",
      "neff",
      "will",
      "willneff",
    ],
    skins: [{ src: "/emotes/neffHyperJAM.gif" }],
  },
  {
    name: "nodders",
    short_names: ["NODDERS"],
    keywords: ["nodders", "nod", "noddies"],
    skins: [{ src: "/emotes/NODDERS.gif" }],
  },
  {
    name: "nopers",
    short_names: ["NOPERS"],
    keywords: ["nopers", "no", "nope"],
    skins: [{ src: "/emotes/NOPERS.gif" }],
  },
  {
    name: "nymncorn",
    short_names: ["nymnCorn"],
    keywords: ["nymncorn", "mmm", "corn", "nymn"],
    skins: [{ src: "/emotes/nymnCorn.gif" }],
  },
  {
    name: "okaychamp",
    short_names: ["OkayChamp"],
    keywords: ["okaychamp", "okay", "champ"],
    skins: [{ src: "/emotes/OkayChamp.png" }],
  },
  {
    name: "omegalul",
    short_names: ["OMEGALUL"],
    keywords: ["omegalul", "lol", "lmao", "lul", "ha", "haha", "ja", "jaja"],
    skins: [{ src: "/emotes/omegalul.png" }],
  },
  {
    name: "oooo",
    short_names: ["OOOO"],
    keywords: ["oooo", "fish"],
    skins: [{ src: "/emotes/OOOO.gif" }],
  },
  {
    name: "pagchomp",
    short_names: ["PagChomp"],
    keywords: ["pagchomp", "pag", "chomp"],
    skins: [{ src: "/emotes/PagChomp.png" }],
  },
  {
    name: "painschamp",
    short_names: ["PainsChamp"],
    keywords: ["painschamp", "pains", "champ", "pain"],
    skins: [{ src: "/emotes/PainsChamp.png" }],
  },
  {
    name: "pausechamp",
    short_names: ["PauseChamp"],
    keywords: ["pausechamp", "pause", "champ"],
    skins: [{ src: "/emotes/PauseChamp.png" }],
  },
  {
    name: "peepoarrive",
    short_names: ["peepoArrive"],
    keywords: [
      "peepoarrive",
      "peepo",
      "pepo",
      "arrive",
      "here",
      "welcome",
      "hey",
      "wave",
      "hi",
      "hello",
      "howdy",
    ],
    skins: [{ src: "/emotes/peepoArrive.gif" }],
  },
  {
    name: "peepobaba",
    short_names: ["peepoBaba"],
    keywords: ["peepobaba", "peepo", "pepo", "baba"],
    skins: [{ src: "/emotes/peepoBaba.png" }],
  },
  {
    name: "peepobye",
    short_names: ["peepoBye"],
    keywords: ["peepobye", "peepo", "pepo", "bye"],
    skins: [{ src: "/emotes/peepoBye.gif" }],
  },
  {
    name: "peepochat",
    short_names: ["peepoChat"],
    keywords: ["peepochat", "peepo", "pepo", "chat"],
    skins: [{ src: "/emotes/peepoChat.gif" }],
  },
  {
    name: "peepocheer",
    short_names: ["peepoCheer"],
    keywords: ["peepocheer", "peepo", "pepo", "cheer"],
    skins: [{ src: "/emotes/peepoCheer.gif" }],
  },
  {
    name: "peepoclap",
    short_names: ["peepoClap"],
    keywords: ["peepoclap", "peepo", "pepo", "clap"],
    skins: [{ src: "/emotes/peepoClap.gif" }],
  },
  {
    name: "peepod",
    short_names: ["peepoD"],
    keywords: ["peepod", "peepo", "pepo"],
    skins: [{ src: "/emotes/peepoD.gif" }],
  },
  {
    name: "peepofat",
    short_names: ["peepoFat"],
    keywords: ["peepofat", "peepo", "pepo", "fat", "houngry", "hungry", "food"],
    skins: [{ src: "/emotes/peepoFat.png" }],
  },
  {
    name: "peepogiggles",
    short_names: ["peepoGiggles"],
    keywords: ["peepogiggles", "pepo", "peepo", "giggle", "giggles"],
    skins: [{ src: "/emotes/peepoGiggles.gif" }],
  },
  {
    name: "peepohey",
    short_names: ["peepoHey"],
    keywords: [
      "peepohey",
      "peepo",
      "wave",
      "pepo",
      "hey",
      "hi",
      "hello",
      "howdy",
      "welcome",
    ],
    skins: [{ src: "/emotes/peepoHey.gif" }],
  },
  {
    name: "peepojammer",
    short_names: ["peepoJAMMER"],
    keywords: ["peepojammer", "peepo", "pepo", "jam", "jammer", "jamjam"],
    skins: [{ src: "/emotes/peepoJAMMER.gif" }],
  },
  {
    name: "peepokiss",
    short_names: ["peepoKiss"],
    keywords: ["peepokiss", "peepo", "pepo", "kiss", "love"],
    skins: [{ src: "/emotes/peepoKiss.png" }],
  },
  {
    name: "peepoleave",
    short_names: ["peepoLeave"],
    keywords: ["peepoleave", "peepo", "pepo", "leave", "exit", "bye"],
    skins: [{ src: "/emotes/peepoLeave.gif" }],
  },
  {
    name: "peepopog",
    short_names: ["peepoPog"],
    keywords: ["peepopog", "peepo", "pepo", "pog"],
    skins: [{ src: "/emotes/peepoPog.png" }],
  },
  {
    name: "peepopogo",
    short_names: ["peepoPogO"],
    keywords: ["peepopogo", "peepo", "pepo", "pog", "pogo"],
    skins: [{ src: "/emotes/peepoPogO.png" }],
  },
  {
    name: "peeporun",
    short_names: ["peepoRun"],
    keywords: ["peeporun", "peepo", "pepo", "run"],
    skins: [{ src: "/emotes/peepoRun.gif" }],
  },
  {
    name: "peeposhy",
    short_names: ["peepoShy"],
    keywords: ["peeposhy", "peepo", "pepo", "shy"],
    skins: [{ src: "/emotes/peepoShy.gif" }],
  },
  {
    name: "peeposnow",
    short_names: ["peepoSnow"],
    keywords: [
      "peeposnow",
      "peepo",
      "pepo",
      "snow",
      "christmas",
      "cold",
      "holidays",
    ],
    skins: [{ src: "/emotes/peepoSnow.gif" }],
  },
  {
    name: "peepot",
    short_names: ["peepoT"],
    keywords: ["peepot", "peepo", "pepo"],
    skins: [{ src: "/emotes/peepoT.gif" }],
  },
  {
    name: "peepoweird",
    short_names: ["peepoWeird"],
    keywords: ["peepoweird", "peepo", "pepo", "weird"],
    skins: [{ src: "/emotes/peepoWeird.png" }],
  },
  {
    name: "pepecd",
    short_names: ["pepeCD"],
    keywords: ["pepecd", "pepe", "cd"],
    skins: [{ src: "/emotes/pepeCD.gif" }],
  },
  {
    name: "pepegehmm",
    short_names: ["PepegeHmm"],
    keywords: ["pepegehmm", "pepege", "pepe", "hmm", "hmmm"],
    skins: [{ src: "/emotes/PepegeHmm.png" }],
  },
  {
    name: "pepehands",
    short_names: ["PepeHands"],
    keywords: ["pepehands", "pepe", "hands"],
    skins: [{ src: "/emotes/PepeHands.png" }],
  },
  {
    name: "pepejamjam",
    short_names: ["pepeJAMJAM"],
    keywords: ["pepejamjam", "pepe", "jam"],
    skins: [{ src: "/emotes/pepeJAMJAM.gif" }],
  },
  {
    name: "pepejam",
    short_names: ["pepeJAM"],
    keywords: ["pepeJAM", "pepe"],
    skins: [{ src: "/emotes/pepejam.gif" }],
  },
  {
    name: "pepela",
    short_names: ["PepeLa"],
    keywords: ["pepela", "pepe"],
    skins: [{ src: "/emotes/PepeLa.png" }],
  },
  {
    name: "pepelaugh",
    short_names: ["PepeLaugh"],
    keywords: ["pepelaugh", "pepe", "laugh"],
    skins: [{ src: "/emotes/PepeLaugh.gif" }],
  },
  {
    name: "pepemeltdown",
    short_names: ["pepeMeltdown"],
    keywords: ["pepemeltdown", "pepe", "meltdown"],
    skins: [{ src: "/emotes/pepeMeltdown.gif" }],
  },
  {
    name: "pepep",
    short_names: ["pepeP"],
    keywords: ["pepep", "pepe"],
    skins: [{ src: "/emotes/pepeP.gif" }],
  },
  {
    name: "pepes",
    short_names: ["PepeS"],
    keywords: ["pepes", "pepe"],
    skins: [{ src: "/emotes/PepeS.gif" }],
  },
  {
    name: "pepespit",
    short_names: ["PepeSpit"],
    keywords: ["pepespit", "pepe", "spit"],
    skins: [{ src: "/emotes/PepeSpit.gif" }],
  },
  {
    name: "pepew",
    short_names: ["pepeW"],
    keywords: ["pepew", "pepe"],
    skins: [{ src: "/emotes/pepeW.gif" }],
  },
  {
    name: "pepog",
    short_names: ["PepoG"],
    keywords: ["pepog", "pepo", "peepo"],
    skins: [{ src: "/emotes/PepoG.png" }],
  },
  {
    name: "pog",
    short_names: ["Pog"],
    keywords: ["pog", "poggies", "pogger", "poggers"],
    skins: [{ src: "/emotes/Pog.png" }],
  },
  {
    name: "poggers",
    short_names: ["POGGERS"],
    keywords: ["poggers", "pog", "poggies", "pogger"],
    skins: [{ src: "/emotes/POGGERS.png" }],
  },
  {
    name: "poggies",
    short_names: ["POGGIES"],
    keywords: ["poggies", "pog", "pogger"],
    skins: [{ src: "/emotes/POGGIES.png" }],
  },
  {
    name: "pogo",
    short_names: ["PogO"],
    keywords: ["pogo", "pog", "azan"],
    skins: [{ src: "/emotes/PogO.png" }],
  },
  {
    name: "pogu",
    short_names: ["PogU"],
    keywords: ["pogu", "pog"],
    skins: [{ src: "/emotes/PogU.png" }],
  },
  {
    name: "pphop",
    short_names: ["ppHop"],
    keywords: ["pphop", "hop"],
    skins: [{ src: "/emotes/ppHop.gif" }],
  },
  {
    name: "ppoverheat",
    short_names: ["ppOverheat"],
    keywords: ["ppoverheat", "overheat"],
    skins: [{ src: "/emotes/ppOverheat.gif" }],
  },
  {
    name: "pppoof",
    short_names: ["ppPoof"],
    keywords: ["pppoof", "poof"],
    skins: [{ src: "/emotes/ppPoof.gif" }],
  },
  {
    name: "prayge",
    short_names: ["Prayge"],
    keywords: ["prayge", "pray", "god"],
    skins: [{ src: "/emotes/Prayge.png" }],
  },
  {
    name: "ratjam",
    short_names: ["ratJAM"],
    keywords: ["ratjam", "rat", "jam"],
    skins: [{ src: "/emotes/ratJAM.gif" }],
  },
  {
    name: "ree",
    short_names: ["REE"],
    keywords: ["ree", "reeee"],
    skins: [{ src: "/emotes/REE.png" }],
  },
  {
    name: "sillychamp",
    short_names: ["SillyChamp"],
    keywords: ["sillychamp", "silly", "champ"],
    skins: [{ src: "/emotes/SillyChamp.png" }],
  },
  {
    name: "smoketime",
    short_names: ["SmokeTime"],
    keywords: ["smoketime", "smoke"],
    skins: [{ src: "/emotes/SmokeTime.gif" }],
  },
  {
    name: "swooner",
    short_names: ["SWOONER"],
    keywords: ["swooner"],
    skins: [{ src: "/emotes/SWOONER.png" }],
  },
  {
    name: "teatime",
    short_names: ["TeaTime"],
    keywords: ["teatime", "tea"],
    skins: [{ src: "/emotes/TeaTime.gif" }],
  },
  {
    name: "tomatotime",
    short_names: ["TomatoTime"],
    keywords: ["tomatotime", "tomato"],
    skins: [{ src: "/emotes/TomatoTime.gif" }],
  },
  {
    name: "unpoggers",
    short_names: ["unPOGGERS"],
    keywords: ["unpoggers", "poggers", "pog", "unpoggies"],
    skins: [{ src: "/emotes/unPOGGERS.png" }],
  },
  {
    name: "weirdchamp",
    short_names: ["WeirdChamp"],
    keywords: ["weirdchamp", "weird", "champ"],
    skins: [{ src: "/emotes/WeirdChamp.png" }],
  },
  {
    name: "weirdge",
    short_names: ["Weirdge"],
    keywords: ["weirdge", "weird"],
    skins: [{ src: "/emotes/Weirdge.png" }],
  },
  {
    name: "whatchamp",
    short_names: ["WhatChamp"],
    keywords: ["whatchamp", "what", "champ"],
    skins: [{ src: "/emotes/WhatChamp.png" }],
  },
  {
    name: "wicked",
    short_names: ["WICKED"],
    keywords: ["wicked"],
    skins: [{ src: "/emotes/WICKED.png" }],
  },
  {
    name: "widepeepohappy",
    short_names: ["widepeepoHappy"],
    keywords: ["widepeepohappy", "peepohappy", "peepo", "happy"],
    skins: [{ src: "/emotes/widepeepoHappy.png" }],
  },
  {
    name: "widepeeposad",
    short_names: ["widepeepoSad"],
    keywords: ["widepeeposad", "peeposad", "peepo", "sad"],
    skins: [{ src: "/emotes/widepeepoSad.png" }],
  },
  {
    name: "winetime",
    short_names: ["WineTime"],
    keywords: ["winetime", "wine"],
    skins: [{ src: "/emotes/WineTime.gif" }],
  },
  {
    name: "yep",
    short_names: ["YEP"],
    keywords: ["yep"],
    skins: [{ src: "/emotes/YEP.png" }],
  },
  {
    name: "zzoomer",
    short_names: ["ZZoomer"],
    keywords: ["zzoomer", "zoomer"],
    skins: [{ src: "/emotes/ZZoomer.gif" }],
  },
  {
    name: "doge3d",
    short_names: ["Doge3D"],
    keywords: ["doge3d", "doge", "3d"],
    skins: [{ src: "/emotes/doge3d.gif" }],
  },
  {
    name: "dogecool",
    short_names: ["DogeCool"],
    keywords: ["dogecool", "doge", "cool"],
    skins: [{ src: "/emotes/dogecool.gif" }],
  },
  {
    name: "thugpepe",
    short_names: ["ThugPepe"],
    keywords: ["dogehouse", "doge", "thugpepe"],
    skins: [{ src: "/emotes/thugpepe.png" }],
  },
  {
    name: "blaze",
    short_names: ["blaze"],
    keywords: ["blaze", "yes", "snark"],
    skins: [{ src: "/emotes/blaze.png" }],
  },
  {
    name: "blobdance",
    short_names: ["blobDance"],
    keywords: ["blobDance", "vibe"],
    skins: [{ src: "/emotes/blobdance.gif" }],
  },
  {
    name: "pepepls",
    short_names: ["PepePls"],
    keywords: ["PepePls", "pepe"],
    skins: [{ src: "/emotes/pepepls.gif" }],
  },
  {
    name: "feelsgoodman",
    short_names: ["FeelsGoodMan"],
    keywords: ["FeelsGoodMan", "pepe"],
    skins: [{ src: "/emotes/feelsgoodman.png" }],
  },
  {
    name: "github",
    short_names: ["GitHub"],
    keywords: ["app", "git", "github"],
    skins: [{ src: "/emotes/github.png" }],
  },
  {
    name: "elixir",
    short_names: ["Elixir"],
    keywords: ["app", "elixir"],
    skins: [{ src: "/emotes/elixir.png" }],
  },
  {
    name: "nextjs",
    short_names: ["NextJS"],
    keywords: ["app", "next", "js"],
    skins: [{ src: "/emotes/nextjs.png" }],
  },
  {
    name: "react",
    short_names: ["React"],
    keywords: ["app", "react", "js"],
    skins: [{ src: "/emotes/react.png" }],
  },
  {
    name: "electron",
    short_names: ["Electron"],
    keywords: ["app", "electron"],
    skins: [{ src: "/emotes/electron.png" }],
  },
  {
    name: "beardguyr",
    short_names: ["BeardGuyR"],
    keywords: ["meme", "beard", "guy"],
    skins: [{ src: "/emotes/beardguyright.png" }],
  },
  {
    name: "beardguyl",
    short_names: ["BeardGuyL"],
    keywords: ["meme", "beard", "guy"],
    skins: [{ src: "/emotes/beardguyleft.png" }],
  },
  {
    name: "mememan",
    short_names: ["MemeMan"],
    keywords: ["meme", "guy"],
    skins: [{ src: "/emotes/mememan.png" }],
  },
  {
    name: "npc",
    short_names: ["NPC"],
    keywords: ["meme", "npc", "guy"],
    skins: [{ src: "/emotes/npc.png" }],
  },
  {
    name: "smudgecat",
    short_names: ["SMudgeCat"],
    keywords: ["meme", "cat"],
    skins: [{ src: "/emotes/smudgecat.png" }],
  },
  {
    name: "stonks",
    short_names: ["Stonks"],
    keywords: ["meme", "crypto", "guy"],
    skins: [{ src: "/emotes/stonks.png" }],
  },
  {
    name: "stinks",
    short_names: ["Stinks"],
    keywords: ["meme", "crypto", "guy"],
    skins: [{ src: "/emotes/stinks.png" }],
  },
  {
    name: "iwmd",
    short_names: ["IWMD"],
    keywords: ["meme", "dude", "wednesday", "frog"],
    skins: [{ src: "/emotes/wednesday.png" }],
  },
  {
    name: "presponge",
    short_names: ["PreSponge"],
    keywords: ["meme", "spongebob"],
    skins: [{ src: "/emotes/presponge.png" }],
  },
  {
    name: "spongebob",
    short_names: ["sPonGeBoB"],
    keywords: ["meme", "spongebob"],
    skins: [{ src: "/emotes/sPonGeBoB.png" }],
  },
  {
    name: "peepohappy",
    short_names: ["peepohappy"],
    keywords: ["peepohappy", "peepo", "pepe"],
    skins: [{ src: "/emotes/peepohappy.png" }],
  },
  {
    name: "peepohug",
    short_names: ["peepohug"],
    keywords: ["peepohug", "peepo", "pepe"],
    skins: [{ src: "/emotes/peepohug.png" }],
  },
  {
    name: "purpledogehouse",
    short_names: ["PurpleDogeHouse"],
    keywords: ["purple", "dogehouse", "doge"],
    skins: [{ src: "/emotes/purpledogehouse.png" }],
  },
  {
    name: "widepeepopussy",
    short_names: ["widepeepoPussy"],
    keywords: ["widepeepoPussy", "peepo", "wide"],
    skins: [{ src: "/emotes/widepeepoPussy.png" }],
  },
  {
    name: "rareparrot",
    short_names: ["RareParrot"],
    keywords: ["Rare", "Parrot", "party"],
    skins: [{ src: "/emotes/rareParrot.gif" }],
  },
  {
    name: "orangedogehouse",
    short_names: ["OrangeDogeHouse"],
    keywords: ["orange", "dogehouse", "doge"],
    skins: [{ src: "/emotes/orangedogehouse.png" }],
  },
  {
    name: "cyandogehouse",
    short_names: ["CyanDogeHouse"],
    keywords: ["cyan", "dogehouse", "doge"],
    skins: [{ src: "/emotes/cyandogehouse.png" }],
  },
  {
    name: "angrykermit",
    short_names: ["AngryKermit"],
    keywords: ["kermit", "angry", "ak47"],
    skins: [{ src: "/emotes/angrykermit.png" }],
  },
  {
    name: "darthkermit",
    short_names: ["DarthKermit"],
    keywords: ["kermit", "star", "wars", "darth"],
    skins: [{ src: "/emotes/darthkermit.png" }],
  },
  {
    name: "takemymoney",
    short_names: ["TakeMyMoney"],
    keywords: ["take", "my", "money", "shut", "up"],
    skins: [{ src: "/emotes/takemymoney.png" }],
  },
  {
    name: "awyeah",
    short_names: ["awyeah"],
    keywords: ["aw", "yeah", "awyeah", "dancing"],
    skins: [{ src: "/emotes/awyeah.gif" }],
  },
  {
    name: "ztlul",
    short_names: ["ztlul", "zerotwolul"],
    keywords: ["lul", "lol", "anime", "girl", "zerotwo"],
    skins: [{ src: "/emotes/zerotwolul.png" }],
  },
  {
    name: "ztsmug",
    short_names: ["ztsmug", "zerotwosmug"],
    keywords: ["smug", "anime", "girl", "zerotwo"],
    skins: [{ src: "/emotes/zerotwosmug.png" }],
  },
  {
    name: "ztthinking",
    short_names: ["ztthinking"],
    keywords: [
      "thinking",
      "think",
      "anime",
      "girl",
      "zerotwo",
      "zerotwothinking",
    ],
    skins: [{ src: "/emotes/zerotwothinking.png" }],
  },
  {
    name: "partyparrot",
    short_names: ["partyparrot"],
    keywords: ["party", "high", "parrot", "fun"],
    skins: [{ src: "/emotes/PartyParrot.gif" }],
  },
  {
    name: "dogepls",
    short_names: ["dogepls"],
    keywords: ["doge", "please", "fun", "dance"],
    skins: [{ src: "/emotes/DogePls.gif" }],
  },
  {
    name: "catdance",
    short_names: ["catDance"],
    keywords: ["cat", "dance", "party", "fun"],
    skins: [{ src: "/emotes/catDance.gif" }],
  },
  {
    name: "doughdoge",
    short_names: ["doughdoge"],
    keywords: ["dough", "doge", "pizza"],
    skins: [{ src: "/emotes/doughdoge.png" }],
  },
];


export const customEmojis = [
  {
    id: "emotes",
    name: "Emotes",
    emojis,
  },
];

export const emoteMap: Record<string, string> = {};

emojis.forEach((e: any) => {
  emoteMap[e.name] = e.skins[0].src;
});